In [2]:
# Step 1. NumPyをインポートするコード
import numpy as np

# Step 2. AとBの行列を格納する多次元配列のコード
A = np.array([[0, 1],
              [2, 3],
              [4, 5]])

B = np.array([[0, 1, 2, 3],
              [4, 5, 6, 7]])

# Step 3. 行列の積の計算をするコード
matrix_product = np.dot(A, B)

# Step 4. Step3.の計算結果を表示するコード
print(matrix_product)

# Step 5. 行列の要素の最大値を求めるコード
max_value = np.max(matrix_product)
print(max_value)

[[ 4  5  6  7]
 [12 17 22 27]
 [20 29 38 47]]
47
